### PR TITLE
[cronner] include cronner recipe if property set to true

### PR DESCRIPTION
**Pull request by fujin**
* this enables the code to be added during a patch release (no functional
  change)

### CODE REVIEW

**Comment by theckman** [comment]
I'm trying to fully understand the change, and wonder when you would want to install a cron job that uses `cronner` but doesn't install it. Should we just install it by default, and say using a `cron_d` resource implies the consumer wanting `cronner` to be installed?

**Comment by fujin** [comment]
@theckman i'm fine with that. it looks like https://github.com/theckman/cookbook-cronner/blob/master/test/fixtures/cookbooks/cronner_lwrp_test/recipes/default.rb#L19 here it `include_recipe 'cronner'` before using the cronner lwrp anyway, like it's implicit.

**Comment by theckman** [comment]
@fujin Yeah. The fact I did that there is probably a sign that I wasn't thinking ahead. Silly me. I think it'd be safe to just include by default. :+1:

**Review by theckman — APPROVED** [review]
```
  File /opt/cronner-linux-amd64-v0.5.0
     ✔  should be directory
  File /opt/cronner-linux-amd64-v0.5.0/cronner
     ✔  should be file
     ✔  should be executable
     ✔  should be readable
  File /usr/local/bin/cronner
     ✔  should be file
     ✔  should be symlink
     ✔  should be linked to "/opt/cronner-linux-amd64-v0.5.0/cronner"
  File /etc/cron.d/test_job
     ✔  should be file

Test Summary: 8 successful, 0 failures, 0 skipped
       Finished verifying <lwrp-ubuntu-1604> (0m0.31s).
-----> Destroying <lwrp-ubuntu-1604>...
       ==> default: Forcing shutdown of VM...
       ==> default: Destroying VM and associated drives...
       Vagrant instance <lwrp-ubuntu-1604> destroyed.
       Finished destroying <lwrp-ubuntu-1604> (0m4.23s).
       Finished testing <lwrp-ubuntu-1604> (0m52.85s).
-----> Kitchen is finished. (0m54.01s)
```

**Pull request merged**
