### PR TITLE
Refactor for Chef >= 14.4

### PR DESCRIPTION
**Pull request by jeffbyrnes**
This closes #12 and closes #13 by refactoring what those two pull requests do, in addition to updating the cookbook to work with the now built-in `cron_d` resource, at the expense of requiring Chef >= 14.4.

It also makes plenty of improvements to testing.

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
Added d2faa0c, which fixes Chef 16 compatibility.

**Comment by theckman** [comment]
I don't personally use Chef anymore, so I don't feel able to review this. Going to merge as-is.

Thank you!

**Comment by jeffbyrnes** [comment]
@theckman thanks for merging it!

If you want to add me as a contributor, and invite me to [release to Supermarket](https://supermarket.chef.io/cookbooks/cronner), I’d be happy to take care of this cookbook (which I still use, and I know at least one of my former employers does, too).

**Comment by theckman** [comment]
@jeffbyrnes are you able to confirm your supermarket username?

**Comment by theckman** [comment]
In the interim I've added you at least as a contributor to this repo, and will get you added to the supermarket once I have that confirmation.

**Comment by jeffbyrnes** [comment]
Thanks! My supermarket username is `jeffbyrnes`

**Comment by theckman** [comment]
@jeffbyrnes done!

**Comment by jeffbyrnes** [comment]
Thanks! I’ll take good care 🙂

**Pull request merged**
